import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseCgmCsv, parseTimestamp, splitCsvLine } from '../betawise/js/parse.js';

test('parses Dexcom Clarity export, skipping non-EGV rows', () => {
  const csv = [
    'Index,Timestamp (YYYY-MM-DDThh:mm:ss),Event Type,Event Subtype,Patient Info,Device Info,Source Device ID,Glucose Value (mg/dL),Insulin Value (u),Carb Value (grams)',
    '1,,FirstName,,Jane,,,,,',
    '2,2026-09-01T08:00:00,EGV,,,,iPhone,120,,',
    '3,2026-09-01T08:05:00,EGV,,,,iPhone,Low,,',
    '4,2026-09-01T08:07:00,Carbs,,,,iPhone,,,30',
    '5,2026-09-01T08:10:00,EGV,,,,iPhone,High,,',
  ].join('\n');
  const { readings, source, unit } = parseCgmCsv(csv);
  assert.equal(source, 'Dexcom Clarity');
  assert.equal(unit, 'mgdl');
  assert.deepEqual(readings.map((r) => r.v), [120, 40, 400]);
  assert.equal(new Date(readings[0].t).getHours(), 8);
});

test('parses LibreView export in mmol/L with preamble line', () => {
  const csv = [
    'Glucose Data,Generated on,09-10-2026 10:00 UTC,Generated by,Jane Doe',
    'Device,Serial Number,Device Timestamp,Record Type,Historic Glucose mmol/L,Scan Glucose mmol/L',
    'FreeStyle Libre 3,ABC,09-01-2026 08:00,0,6.7,',
    'FreeStyle Libre 3,ABC,09-01-2026 08:15,1,,7.2',
  ].join('\n');
  const { readings, source, unit } = parseCgmCsv(csv);
  assert.equal(source, 'LibreView');
  assert.equal(unit, 'mmol');
  assert.deepEqual(readings.map((r) => r.v), [121, 130]);
});

test('timestamps with AM/PM and day-first fallbacks', () => {
  assert.equal(new Date(parseTimestamp('09/01/2026 1:30 PM')).getHours(), 13);
  assert.equal(new Date(parseTimestamp('25-09-2026 07:00')).getMonth(), 8);
});

test('quoted CSV fields with commas', () => {
  assert.deepEqual(splitCsvLine('a,"b, c",d'), ['a', 'b, c', 'd']);
});
